# Generated by Django 5.0.2 on 2024-04-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
    ]
