# Generated by Django 5.0.2 on 2024-04-08 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_module', '0002_remove_user_role_id'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='role.role'),
            preserve_default=False,
        ),
    ]
